"""add applications templates action logs exception logs document status

Revision ID: 1976400f7acf
Revises: e3775da7d83e
Create Date: 2026-06-20 18:34:09.814586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1976400f7acf'
down_revision: Union[str, Sequence[str], None] = 'e3775da7d83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action'), 'action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_action_logs_entity_id'), 'action_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_action_logs_entity_type'), 'action_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_action_logs_user_id'), 'action_logs', ['user_id'], unique=False)
    op.create_table('exception_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_logs_error_type'), 'exception_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_exception_logs_user_id'), 'exception_logs', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.execute("ALTER TABLE templates ALTER COLUMN document_type TYPE document_type USING document_type::document_type")
    op.create_index(op.f('ix_templates_created_by_user_id'), 'templates', ['created_by_user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'approved', 'rejected', name='application_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_apartment_id'), 'applications', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_applications_reviewed_by_user_id'), 'applications', ['reviewed_by_user_id'], unique=False)
    op.execute("CREATE TYPE document_status AS ENUM ('sent', 'signed', 'approved', 'rejected')")
    op.add_column('documents', sa.Column('status', sa.Enum('sent', 'signed', 'approved', 'rejected', name='document_status', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    op.execute("DROP TYPE IF EXISTS document_status")
    op.drop_index(op.f('ix_applications_reviewed_by_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_apartment_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_templates_created_by_user_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_exception_logs_user_id'), table_name='exception_logs')
    op.drop_index(op.f('ix_exception_logs_error_type'), table_name='exception_logs')
    op.drop_table('exception_logs')
    op.drop_index(op.f('ix_action_logs_user_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_entity_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_entity_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
