"""initial schema

Revision ID: e3775da7d83e
Revises: 
Create Date: 2026-06-19 22:07:41.524007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3775da7d83e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_request_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id_type', sa.Enum('passport', 'national_id', 'drivers_license', name='id_type'), nullable=False),
    sa.Column('id_number_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('id_number_hash', sa.String(length=64), nullable=False),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('id_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('tenant', 'owner', 'staff', 'admin', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number_hash')
    )
    op.create_table('owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('user_id IS NOT NULL OR company_name IS NOT NULL', name='chk_owner_has_identity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_since', sa.Date(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('background_check_status', sa.Enum('pending', 'passed', 'failed', 'waived', name='background_check_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('apartments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=False),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('square_footage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('vacant', 'occupied', 'maintenance', 'unlisted', name='apartment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_number')
    )
    op.create_table('apartment_amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('amenity_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartment_id', 'amenity_name', name='uq_apartment_amenity')
    )
    op.create_table('leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('lease_start', sa.Date(), nullable=False),
    sa.Column('lease_end', sa.Date(), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'ended', 'terminated', name='lease_status'), nullable=False),
    sa.Column('termination_reason', sa.Enum('non_payment', 'lease_violation', 'tenant_request', 'owner_request', 'property_damage', 'other', name='lease_termination_reason'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('lease_end > lease_start', name='chk_lease_dates'),
    sa.CheckConstraint('move_out_date IS NULL OR move_in_date IS NULL OR move_out_date >= move_in_date', name='chk_move_out_after_in'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('lease_id', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'emergency', name='maintenance_priority'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['maintenance_request_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_apartment_id'), 'maintenance_requests', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_lease_id'), 'maintenance_requests', ['lease_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_tenant_id'), 'maintenance_requests', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('payment_type', sa.Enum('rent', 'service_charge', 'deposit', name='payment_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue', 'partial', 'cancelled', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_request_id', sa.UUID(), nullable=True),
    sa.Column('apartment_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('lease_agreement', 'lease_addendum', 'renewal_letter', 'id_document', 'background_check', 'employment_letter', 'maintenance_quote', 'maintenance_invoice', 'maintenance_photo', 'floor_plan', 'inspection_certificate', 'title_document', 'other', name='document_type'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('\n            (\n                (lease_id IS NOT NULL)::int +\n                (tenant_id IS NOT NULL)::int +\n                (maintenance_request_id IS NOT NULL)::int +\n                (apartment_id IS NOT NULL)::int\n            ) = 1\n            ', name='chk_document_belongs_to_exactly_one_entity'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_apartment_id'), 'documents', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_documents_lease_id'), 'documents', ['lease_id'], unique=False)
    op.create_index(op.f('ix_documents_maintenance_request_id'), 'documents', ['maintenance_request_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_maintenance_request_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_lease_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_apartment_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('payments')
    op.drop_index(op.f('ix_maintenance_requests_tenant_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_lease_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_apartment_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_table('leases')
    op.drop_table('apartment_amenities')
    op.drop_table('apartments')
    op.drop_table('tenants')
    op.drop_table('owners')
    op.drop_table('users')
    op.drop_table('maintenance_request_statuses')
    # ### end Alembic commands ###
